logger implementation
Naveenkumar-ramesh/EmployeeManagementSystem pull request #5
Opened 2022-10-12 10:36 UTC by Naveenkumar-ramesh

2022-10-12 13:13 UTC, ponvel-i2i requested changes

2022-10-12 13:13 UTC, ponvel-i2i commented on com/ideas2it/employee/view/EmployeeView.java
>              } else {
Add the search param in this log

2022-10-12 13:13 UTC, ponvel-i2i commented on com/ideas2it/employee/view/EmployeeView.java
>              if (employeeController.updateEmployee(employeeDTO)) {
Add the employee Id in this log. Without employedd Id, what is purpose of this log

2022-10-12 13:13 UTC, ponvel-i2i commented on com/ideas2it/employee/view/EmployeeView.java
>              if (employeeController.deleteEmployee(employeeId) != false) {
Add the deleted employedd Id

2022-10-13 07:30 UTC, aruni2isankar approved these changes

2022-10-17 05:47 UTC, merged